INSERT INTO product VALUES ('FISW01', 'Angelfish', 'Saltwater fish from Australia', 'FISH');
INSERT INTO product VALUES ('FISW02', 'Tiger Shark', 'Saltwater fish from Australia', 'FISH');
INSERT INTO product VALUES ('FIFW01', 'Koi', 'Freshwater fish from Japan', 'FISH');
INSERT INTO product VALUES ('FIFW02', 'Goldfish', 'Freshwater fish from China', 'FISH');
INSERT INTO product VALUES ('K9BD01', 'Bulldog', 'Friendly dog from England', 'DOGS');
INSERT INTO product VALUES ('K9PO02', 'Poodle', 'Cute dog from France', 'DOGS');
INSERT INTO product VALUES ('K9DL01', 'Dalmation', 'Great dog for a fire station', 'DOGS');
INSERT INTO product VALUES ('K9RT01', 'Golden Retriever', 'Great family dog', 'DOGS');
INSERT INTO product VALUES ('K9RT02', 'Labrador Retriever', 'Great hunting dog', 'DOGS');
INSERT INTO product VALUES ('K9CW01', 'Chihuahua', 'Great companion dog', 'DOGS');
INSERT INTO product VALUES ('RPSN01', 'Rattlesnake', 'Doubles as a watch dog', 'REPTILES');
INSERT INTO product VALUES ('RPLI02', 'Iguana', 'Friendly green friend', 'REPTILES');
INSERT INTO product VALUES ('FLDSH01', 'Manx', 'Great for reducing mouse populations', 'CATS');
INSERT INTO product VALUES ('FLDLH02', 'Persian', 'Friendly house cat, doubles as a princess', 'CATS');
INSERT INTO product VALUES ('AVCB01', 'Amazon Parrot', 'Great companion for up to 75 years', 'BIRDS');
INSERT INTO product VALUES ('AVSB02', 'Finch', 'Great stress reliever', 'BIRDS');
