version: "3.9"
services:
  db:
    container_name: tp04
    image: mariadb:10.8.3-jammy
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: glg203
      MARIADB_DATABASE: petstore03

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    links:
      - db:db
